language: node_js
branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
node_js:
  - '12'
  - '10'
  - '8'
before_install:
  - 'npm install -g npm@latest'
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
