environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install

version: '{build}'

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm test

build: off
